name: matchbox

services:
  bot:
    container_name: matchbox-bot
    image: ghcr.io/vidhanio/matchbox:latest
    build: .
    environment:
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      GUILDS: $GUILDS
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@database:5432/$POSTGRES_DB

  database:
    container_name: matchbox-database
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  default:
    name: matchbox-network
volumes:
  database:
    name: matchbox-database
    driver: local
