name: scheduletf

services:
  bot:
    container_name: scheduletf-bot
    image: ghcr.io/vidhanio/scheduletf:latest
    build: .
    environment:
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      GUILDS: $GUILDS
      DATABASE_URL: $DATABASE_URL

  database:
    container_name: scheduletf-database
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  default:
    name: scheduletf-network
volumes:
  database:
    name: scheduletf-database
    driver: local
