[licenses]
allow = [
    "AGPL-3.0",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]

    [[licenses.clarify]]
    name = "ring"

    expression = "ISC AND MIT AND OpenSSL"
    license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[advisories]
ignore = ["RUSTSEC-2024-0370", "RUSTSEC-2024-0436"]
