app = 'scheduletf'
primary_region = 'yyz'

[build]

[env]
PRODUCTION = 'true'

[http_service]
auto_start_machines = true
auto_stop_machines = 'stop'
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
