app = 'matchbox'
primary_region = 'lax'

[build]
image = 'registry.fly.io/matchbox:latest'

[env]
PRODUCTION = 'true'

[[mounts]]
destination = '/data'
source = 'matchbox_data'

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
